### ISSUE TITLE
iOS Fatal Error - [__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

### ISSUE THREAD

**Issue by mitch104** [getsentry/react-native-sentry#138]
"react-native-sentry": "^0.14.1",
"react-native": "0.45.1",
XCode: 8.3.3

Occurs on both physical and simulator devices on release and debug configurations (when Sentry installed).

Full Exception:

```
Terminating app due to uncaught exception 'RCTFatalException: Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]' was thrown while invoking setUser on target RNSentry with params (
        {
        email = "rich@somewhere.io";
        id = 59393dcdc898af00011fea32;
    },
        {
        "__sentry_stack" = "enqueueNativeCall@file:///var/containers/Bundle/Application/BA4026A2-3F53-4570-96B...
        ...
        ...p/main.jsbundle:29:1173\nvalue@[native code]";
    }
)', reason: 'Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]:...'
```

NB: The `...` are not in the original `__sentry_stack` string

**Comment by benhowes** [comment]
Looking at this more, we've found the problem is that coming from a working android implementation, we can use `id` instead of `userID` in the android version, due to https://github.com/getsentry/react-native-sentry/blob/ae8fc85b9cc7a637407263e9d9dcb00e91f74c56/android/src/main/java/io/sentry/RNSentryModule.java#L242, however this functionality is not present in the iOS native code.

Not sure what your preferred solution is, however it would make more sense if it was consistent over platforms @HazAT

**Comment by jeroenbourgois** [comment]
Hi

This should have been solved now, seems related to #98

**Comment by benhowes** [comment]
@jeroenbourgois certainly is related, however you'll see we were testing with 0.14.1 which was released today. The issue is clearly described and a really easy fix, but not urgent from our end, since we can just use `userID` on both platforms.

**Comment by HazAT** [comment]
In the latest release `>= 0.14.10` I've added support for 
`userId`
`userID`
`id`
so this shouldn't anymore.
