### ISSUE TITLE
No sourcemaps with js error

### ISSUE THREAD

**Issue by maximmcnair** [getsentry/react-native-sentry#151]
Setup basic project with `react-native init sentrytest` and deps `"react-native": "0.46.3", "react-native-sentry": "^0.14.5"`.

No errors though builds with either `react-native run-ios` or through xcode. Says files are uploaded. However when i throw an error:
```
  componentDidMount() {
    throw new Error('sentry: test')
  }
```
<img width="1011" alt="screen shot 2017-07-15 at 11 15 08" src="https://user-images.githubusercontent.com/1009787/28238587-e77071f4-694e-11e7-822f-2812bbf23b6e.png">

**Comment by HazAT** [comment]
Hey,
We do not upload sourcemaps for debug builds by default.
You can however enable it https://docs.sentry.io/clients/react-native/manual-setup/#build-steps
> Note that uploading of debug simulator builds by default is disabled for speed reasons. If you do want to also generate debug symbols for debug builds you can pass --allow-fetch as a parameter to react-native-xcode in the above mentioned build phase.

**Comment by slicejunk** [comment]
@HazAT 
I have a similar issue:
- rn 0.46.4
- while testing on a real IOS device in Debug config (prebundled source on the device)
- sourcemaps are uploaded correctly since they appear as "~/bundle.sourcemap.js"  on release/artifacts page for the correct dist number
- the error is: "Source code was not found for app:///index.ios.bundle"

the source maps where upload either from the xcode hook during the build phase or manually:

```node_modules/sentry-cli-binary/bin/sentry-cli  --auth-token<auth_token> releases -p <project_slug> -o <org> files <release_name>  upload-sourcemaps --dist <dist_number> --rewrite <path_to_sourcemap.js>```


Help please !!

**Comment by HazAT** [comment]
To always make it work you shoud add `--allow-fetch` in you Xcode build step `Bundle React Native code and images`.
If you called `react-native link react-native-sentry` this should be already there, if not it should look like this.

```
export SENTRY_PROPERTIES=sentry.properties
export NODE_BINARY=node
../node_modules/sentry-cli-binary/bin/sentry-cli react-native xcode --allow-fetch ../node_modules/react-native/scripts/react-native-xcode.sh
```

We disabled it for all debug builds since people tend to change a lot during development without building the app again in Xcode. If the app isn't built in Xcode this script is not called and therefore no sourcemaps will be uploaded.

**Comment by HazAT** [comment]
Hey, please upgrade to `0.15.0` this should be resolved.
