### ISSUE TITLE
[question] Integration tests

### ISSUE THREAD

**Issue by benhowes** [getsentry/react-native-sentry#152]
We're using react-native-sentry on a production project (after getting a few fixes in), however we're currently deploying from our own fork because we've found that this project isn't all that stable yet (don't get me wrong though, it's really useful!).

Do you have plans for implementing integration tests?

I can see they would end up being rather complex, however it seems that you need:
1. A test project which can log exceptions, probably with buttons to trigger them
2. An appium runner which can press those buttons
3. A mocked up sentry server which will verify the exceptions coming in

As far as I can tell, this would let you catch a lot of problems before a release goes out.

**Comment by HazAT** [comment]
That's definitely something on our roadmap.
Currently, we are still in the process of catching up with react-native itself since they also introduce many changes with every (monthly) release.
We want to have our own test app which does exactly what you described.
So thanks for bringing that up, we are working on it 👍

**Comment by HazAT** [comment]
@benhowes 
Tests are almost up and running :) 
https://github.com/getsentry/react-native-sentry/pull/170
