### ISSUE TITLE
Symbols always uploaded, even for dev

### ISSUE THREAD

**Issue by benhowes** [getsentry/react-native-sentry#174]
I'm not sure if this is a big problem, however in android and iOS, symbols are always uploaded, even for dev builds. Is there a way this can be skipped for dev? Happy to implement it if I can have some pointers?

Thanks!

**Comment by HazAT** [comment]
Hey, the upload of debug symbols shouldn't be a problem, since it happens in background and does not block the build process. 
The sourcemaps however should be disabled, since there is no quick and easy way to upload them for every code change.
You can skip it now if you change the run script in Xcode.

**Comment by HazAT** [comment]
I will close this for now since there is nothing we can do here at the moment.
