### ISSUE TITLE
when i build it for android ,it went failed，but i can run it on my Simulator

### ISSUE THREAD

**Issue by sayhei** [getsentry/react-native-sentry#222]
* Where:
Script '/Users/garry/Code/jhd/node_modules/react-native-sentry/sentry.gradle' line: 126

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssetsdebugSentryUpload'.
> A problem occurred starting process 'command 'node_modulessentry-cli-binarybinsentry-cli''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by HazAT** [comment]
`A problem occurred starting process 'command 'node_modulessentry-cli-binarybinsentry-cli''` is this a paste error that the `/` are missing?
Because there should be `/` in the path so the process is able to find the `sentry-cli` binary.

With running it in Simulator you mean iOS or the Android simulator?

Can you check the content of you `sentry.properties` file and check the path of the cli in there.

**Comment by zackify** [comment]
Same thing happening for me

**Comment by HazAT** [comment]
Can you guys please send me the content of `sentry.properties` and strip the sensitive data?

**Comment by zackify** [comment]
```
defaults.url=https://sentry.io/
defaults.org=org name
defaults.project=project name
auth.token=token
cli.executable=/Users/zach/Projects/receiptdefender/app/node_modules/sentry-cli-binary/bin/sentry-cli
```

here you go!

**Comment by Bernhard---H** [comment]
I have the same problem, but my `sentry.properties` file looks like that:
```properties
defaults.url=https://sentry.io/
defaults.org=org
defaults.project=project
auth.token=token
cli.executable=node_modules\sentry-cli-binary\bin\sentry-cli
```

**I found a bug-fix:** 
On Windows I have to change the last line to:
```properties
cli.executable=node_modules\\sentry-cli-binary\\bin\\sentry-cli
```
And on Linux:
```properties
cli.executable=node_modules/sentry-cli-binary/bin/sentry-cli
```

Is there a way to make the same path work on both platforms without changing it?

**Comment by HazAT** [comment]
@Bernhard---H You can install `sentry-cli` globally and remove the `cli.executable` line overall.
@zackify Make sure the path `/Users/zach/Projects/app/node_modules/sentry-cli-binary/bin/sentry-cli` exsits (if you build it not on your machine).
Also, the absolute path should be fixed in the latest version, so it should be a relative path.

There are 3 ways to install `sentry-cli` globally:
see: https://github.com/getsentry/sentry-cli#sentry-cli

**Comment by zackify** [comment]
Ah thanks, didn't even realize I renamed my folder and that it wasn't relative. haha

**Comment by cinder92** [comment]
im having same issue

sentry.properties

```
defaults.url=https://sentry.io/
defaults.org=org
defaults.project=project
auth.token=token
cli.executable=node_modules/sentry-cli-binary/bin/sentry-cli
```

Error

![captura de pantalla 2017-09-21 a la s 11 23 48](https://user-images.githubusercontent.com/4725556/30706885-5fe489fe-9ebf-11e7-80e2-a109518be652.jpg)

any idea?

**Comment by crazy4groovy** [comment]
@cinder92 FWIW this seems to work better for me (on Windows):

`cli.executable=node_modules\\sentry-cli-binary\\bin\\sentry-cli`

**Comment by cinder92** [comment]
@crazy4groovy im on mac, but that file is not the error :/

**Comment by CyxouD** [comment]
For me error occurred because I had `cli.executable=node_modules/@sentry/react-native/node_modules/@sentry/cli/bin/sentry-cli` (incorrect path)  instead of `cli.executable=node_modules/@sentry/cli/bin/sentry-cli` in `android/sentry.propetries`.
It looks like it happened when upgrading from `react-native-sentry` and running `yarn sentry-wizard -i reactNative -p ios android`

**Comment by leotm** [comment]
I had similar to @CyxouD, had to update my _sentry.properties_ from the invalid `cli.executable=node_modules/@sentry/wizard/node_modules/@sentry/cli/bin/sentry-cli` to valid `cli.executable=node_modules/@sentry/cli/bin/sentry-cli`
