### ISSUE TITLE
Upload debug symbol in development ?

### ISSUE THREAD

**Issue by KkkkKernc** [getsentry/react-native-sentry#238]
OS:
- [x]  MacOS

_Platform:_
- [x]  iOS

Hi there,
  i'm using this lib with version 0.21.1 && rn version is 0.44.0, and it works fine.
  but recently i found it upload debug symbol automatical when i using ios simulator in development.
  it makes me confused, i didn't change any code and it happened.
  is there a way to resolve this porblem? thx!

**Comment by HazAT** [comment]
Uploading the debug symbols is not a real issue, sentry-cli runs in background and uploads the dSYMs.
I am not really sure though why it suddenly started.
To disable it you have to change the run script in Xcode to exclude DEBUG builds.

**Comment by MrHubble** [comment]
@HazAT are you able to elaborate on which script needs to be changed (ie name and location) and how to change it? Thanks.

Reference:

>To disable it you have to change the run script in Xcode to exclude DEBUG builds.

**Comment by gianpaj** [comment]
Same question here. Instead of manually disabling the upload of debug symbols for every Debug build, how could we set this for all Xcode Debug builds AND also via an ENV variable when running `react-native run-ios`?

For example (suggestion):
```
SKIP_SENTRY_UPLOAD=true react-native run-ios
```

disabling manually (thumbs down)
<img width="847" alt="onova_xcodeproj" src="https://user-images.githubusercontent.com/899175/49639606-172e4b80-fa14-11e8-92f2-73350122dde2.png">

We have a horrible internet connection, and uploading few megabytes takes minutes :'(

Thanks

**Comment by kesha-antonov** [comment]
@HazAT Hey! Please advice

```
export SENTRY_PROPERTIES=sentry.properties

# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"

../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

How to force this script to upload only not DEBUG builds?

**Comment by kesha-antonov** [comment]
@gianpaj Thanks!
