### ISSUE TITLE
Best practice for using different DSNs for different stages

### ISSUE THREAD

**Issue by sroze** [getsentry/react-native-sentry#437]
As far as I know, this is how the configuration of the Sentry client needs to happen on a ReactNative application:

1. DSN (and others) need to be in the `ios/sentry.properties` and `android/sentry.properties` files
1. The DSN needs to be accessible within the JavaScript in order to call `Sentry.config(DSN).install()`. We are using react-native-config, which is populating the `DSN` variable from either a `.env` file (or from the plist file for instance).

The thing is: we'd love to be able to identify that some errors are coming from the "staging" or others from the "production" application. What's the best way to handle this? 

_Note that I'm happy that this might be a non-issue if we believe that the application builds should "simply" be promoted from staging to production without any rebuild. Even though it makes little sense as we definitely need different API URLs, etc..._

**Comment by HazAT** [comment]
The preferred way of handling different environments is not to create multiple projects, rather than setting up multiple environments when sending events like:
```
Sentry.setTagsContext({"environment": "production"});
// Sentry.setTagsContext({"environment": "staging"});
```
In Sentry you can filter you issues with the selector on the top right:
![screenshot 2018-07-05 09 35 59](https://user-images.githubusercontent.com/363802/42308787-e781341c-8036-11e8-829d-ce6eadbdd2e1.png)

Hope this answers your question.

**Comment by sroze** [comment]
It does, ish. The point is that in order to call this method with the correct value... I need it to come from somewhere, right? Which, so far, we resolve environment variable at build time. But it means we can't promote the same APK from the Alpha to Beta to Production for example, because we need to build it again for the `production` environment. Do you know about any approach that won't force us to do so?

**Comment by HazAT** [comment]
I am not sure if I fully got your answer but may I ask do you have a staging/prod server where your app is talking to? How do you do it there?
This is now a question of how to track which environment your app is running in, right?
Not sure if Android provides a way of tracking, I am running in Alpha Channel, I am running in Beta channel, if so you could use this. 

I am closing this now since it's not an issue with Sentry anymore but feel free to still reply here.

**Comment by airtonix** [comment]
@HazAT a ReactNative app can't pull different environment variables based on it's execution situation. Unlike a server app, you don't control the environment in which it executes (the users phone), you must create precompiled binaries for each stage.
react-native-config is just glue between some files in the build environment (CICD process), the platforms config layer (ios plist or gradle config) and something like an internal `webpack.DefinePlugin`. This is what @sroze is referring to when they say 

> Which, so far, we resolve environment variable at build time

 So you can't treat the app configuration like you can a server side app configuration.

@sroze Even if you solve getting this value differently at runtime, you'll still have to deal with all your other configuration values being provided at build time. so now you have some of them coming from build time and some coming at runtime... will it be obvious which?
