### ISSUE TITLE
[Question] What is the role of release version and dist ?

### ISSUE THREAD

**Issue by listenzz** [getsentry/react-native-sentry#516]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

What are the usage scenarios of the following three methods?

```ts
  static setRelease(release: string): void;

  static setDist(dist: string): void;

  static setVersion(version: string): void;
```
How does Sentry match sourcemap based on these three?

**Comment by HazAT** [comment]
`release` = Name of the release (full name, you have to check to url in Sentry when clicking on a release)

`dist` = fragmenting a release, you can have one release with multiple `dist` (Distributions) in there
Used for appcenter and stuff where you have release: `1.0` dist: `1` (build number for example)

`setVersion` is a helper function which just sets the version because by default we append the bundle id to the version of the app like
`1.0-bundle.id`

`setVersion` only sets the version part of the string, as where `setRelease` replaces the whole string with what you set.

**Comment by jamesholcomb** [comment]
I need to specify dist in my project.  For Code Push, should setRelease() be called with `bundleid-appversion-codepush:label` where label is v1, v2, etc?

And did you mean _prepend_ the bundle id?  From sentry.gradle, release name is constructed as:

    def releaseName = "${variant.getApplicationId()}-${variant.getVersionName()}"

**Comment by aleclarson** [comment]
@HazAT Assume I'm generating the `release` string with the app name, its version, and the last commit SHA-1 (eg: `foo@1.0.0-a19e221`). Would it be okay to just do `Sentry.setDist('1')`, or would that prevent me from using some feature(s)?

> Used for appcenter and stuff

This part is a little confusing. It's for when I'm publishing a release to multiple app stores?
